### ISSUE TITLE
Wincc

### ISSUE THREAD

**Issue by Qaissmalh** [RobertOrsin/TIAPortalGames#1]
Hi 
I have some problems with wincc I hop you can help me

**Comment by RobertOrsin** [comment]
Sure! What issue do you have?

**Comment by Qaissmalh** [comment]
I want someone how can upgrade HMI working in wincc 6.3 to work in new software with windows 10 I will to pay if you can help me

**Comment by Qaissmalh** [comment]
I have old systems and old pc

**Comment by RobertOrsin** [comment]
Ok I understand, but this repository is not the right place to discuss this. Please write me an email with more details and I will see how I can help you.
