### ISSUE TITLE
Wincc

### ISSUE THREAD

**Issue by huukhoa1412** [RobertOrsin/TIAPortalGames#2]
Hi
I have some problems with wincc I hop you can help me

**Comment by RobertOrsin** [comment]
I try my best, please describe your problem

**Comment by huukhoa1412** [comment]
![GNdaiQ_XEAAdpNv](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/c08720f6-d584-4141-b777-05fcf70d866c)
![GNdYiz9WwAAhncF](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/0c03ec21-6329-4fe6-803a-93f7fa7fdf76)

**Comment by RobertOrsin** [comment]
I recomend switching the projects language to your local one. To get more infos from the error-screen.

This error is caused by the Script AddUser. It creates a UserName in a Textfile. The path is defined as "C:\TestFiles\user.txt".

Create the nessecary folders and files or change the path defines in line 11 of the same script and try again.

**Comment by huukhoa1412** [comment]
I simulate wincc , create foders and files .
Error rpg pokemon 
Gameboy zelda no play game 
![image](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/43f72c64-ade5-4532-802d-7e6d520874bf)
and rpg (pokemon)
![image](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/718c3646-2f4e-4d85-93cb-8712a63cba04)

**Comment by RobertOrsin** [comment]
I need the errorscreens to pin point the issue.

Also, it seems not all graphics are loading. Check the graphicslists and provide me with the errormessages.

**Comment by huukhoa1412** [comment]
Compiling finished (errors: 0; warnings: 162)
![image](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/c66500b2-60c9-4a73-b542-b0f6ba6bcf4b)

**Comment by RobertOrsin** [comment]
What TIA Portal Version are you using? Honestly, from that information alone, i have no clue. If you could provide me with your project, i can have a look.
Currently, i can only work with V16

**Comment by huukhoa1412** [comment]
I use V16
![image](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/f95b3c34-0fae-4dff-b1f6-ce7d92090d59)

I compile project 163 warning
![image](https://github.com/RobertOrsin/TIAPortalGames/assets/59795495/874b2c66-19c0-4fe7-bf6e-c3309257039e)

**Comment by RobertOrsin** [comment]
If you still got the issue and are interested in solving it, please provide me with your project-file.

**Comment by huukhoa1412** [comment]
Yes . my project file 
Link download : https://drive.google.com/file/d/1gHfxUfO9IiNBLCkUpRyCBE9BHkiUuWfi/view
 check my file again

**Comment by RobertOrsin** [comment]
I could run the games just fine. I noticed that the font in your emulation-windows is much bigger then in the editor, or on my emmulator. Is you windows-scaling set to something not 100%...for some reason WinCC takes your scaling and applies it to the panel. Maybe some graphics are affected by this.
Other then that, i have no clue why it is not running, as it is running for me :/ 

Sorry

**Comment by huukhoa1412** [comment]
i failed :(

**Comment by RobertOrsin** [comment]
I am realy sorry :( sometimes siemens is a bitch. Wish i could help you
